const fs = require('fs');
const path = require('path');
const solc = require('solc');

const sourcePath = path.join(__dirname, 'contracts', 'ArbiSyncExecutor.sol');
const sourceCode = fs.readFileSync(sourcePath, 'utf8');

const input = {
  language: 'Solidity',
  sources: {
    'ArbiSyncExecutor.sol': {
      content: sourceCode
    }
  },
  settings: {
    viaIR: true,
    outputSelection: {
      '*': {
        '*': ['abi', 'evm.bytecode']
      }
    },
    optimizer: {
      enabled: true,
      runs: 200
    }
  }
};

console.log("Compiling contract...");
const output = JSON.parse(solc.compile(JSON.stringify(input)));

if (output.errors) {
  let hasError = false;
  output.errors.forEach(err => {
    console.error(err.formattedMessage);
    if (err.severity === 'error') hasError = true;
  });
  if (hasError) {
    process.exit(1);
  }
}

const contractData = output.contracts['ArbiSyncExecutor.sol']['ArbiSyncExecutor'];
const abi = contractData.abi;
const bytecode = contractData.evm.bytecode.object;

const outputPath = path.join(__dirname, 'services', 'compiledContract.ts');
const content = `// Auto-generated by compile.cjs. Do not edit manually.
export const CONTRACT_ABI = ${JSON.stringify(abi, null, 2)};
export const CONTRACT_BYTECODE = "0x${bytecode}";
`;

fs.writeFileSync(outputPath, content, 'utf8');
console.log("Compilation successful! Output saved to services/compiledContract.ts");
